apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: cosmic-coffee
  labels:
    app: backend
data:
  PORT: "3001"
  REDIS_URL: "redis://redis:6379"
  MIDDLEWARE_URL: "http://middleware:3002"
  CART_URL: "http://cart:3003"

