apiVersion: v1
kind: Service
metadata:
  name: middleware
  namespace: cosmic-coffee
  labels:
    app: middleware
    component: middleware
spec:
  type: ClusterIP
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
    name: http
  selector:
    app: middleware

