apiVersion: v1
kind: Service
metadata:
  name: load-generator
  namespace: cosmic-coffee
  labels:
    app: load-generator
    component: testing
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app: load-generator

